### PR TITLE
John 5 0 0

### LINKED ISSUE #109: Checklist for 5.0.0
## Implementations
- [x] Add `Supermassive` Special Power.
- ~~Add `Excalibur` Special Power.~~
- [x] Add `Sigma Strike` Special power that implements `WeaponCriticalEdgeIncreaseStackable`.
- [x] Add `Power leveling` OP ability that increases exp gain using `AddPlayerLeaveCombatTrigger`.
- [x] Add `Signature Strike` to signature move selection.
- ~~Add `Celestial Realm` and `Shadow Realm` as OP abilities (require level 15).~~
- [x] Update TabletopTweaks-Core requirement to 0.5.15.
- [x] Add some wuxia/murim-like backgrounds (#114)
  - [x] Added `Demonic Cultivator` Isekai background. 
  - [x] Added `Enlightened Sage` Isekai background.
  - [x] Added `Musician` Isekai background.
  - [x] Added `Rationalist` Isekai background.
- [x] Class Reworks
  - #108
  - #123
- [x] Rework `Aura of Righteous Wrath`.
  - [x] Add variants
  - [x] Remove effect on additional limbs.
- [x] Change `Killing Intent` into a toggle ability (#101)
- [x] Nerf `Exceptional Weapon` feats to no longer work with additional limbs (remember to update description)
- [x] Nerf `Beta Tester` initiative bonus from 10 -> 4.
- [x] Nerfed Magical Amplification spell dice from d12 -> d10.
- [x] Buffed `Gamer` background from +4 to +8
- [x] Fix `Reflect` to ignore attacks from owner (#125)
- [x] Remove True Smite and True Mark from paladin legacy. (#107)
- [x] Remove redundant `Kinetic Power` Special Power (#107)
- [x] Remove redundant `OverpoweredAbilitySelection2` and just use `OverpoweredAbilitySelection` instead.
- [x] Remove alignment restrictions for Isekai `Channel Positive Energy` and `Channel Negative Energy`.
- [x] Update icon for `Exceptional Feats`.
- [x] add crossbreed human to human heritages
- [x] #122 
- [x] #128 
- [x] Bugfix, selection array initilization logic seems to differ either due to other mods, game version, or just because; making the use of the Features reference proxy array questionable, so instead the underlying m_AllFeatures array needs to be used everywhere #129 

## Pre-Release Tasks
- [x] Update LocalizationPack.json
- [x] Update CHANGELOG.md
- [x] Update README.md
- [x] Update Info.json
- [x] Update Repository.json

## Post-Release Tasks
- Update mod description
- Update mod version
- New screenshots
- Release description

### PR DESCRIPTION
**Pull request by JohN100x1**
resolves #109

### CODE REVIEW

File: IsekaiMod/Utilities/PatchTools.cs [hunk 1]
```diff
@@ -0,0 +1,505 @@
...
+            }
+            if (component is MonkNoArmorFeatureUnlock addUnarmedFact) {
+                var fact = addUnarmedFact.m_NewFact.Get();
+                if (fact != null) {
+                    if (fact is BlueprintFeature feature2) {
+                        PatchClassIntoFeatureOfReferenceClass(feature2, myClass, referenceClass, mylevel, loopPrevention);
+                    }
+                    if (fact is BlueprintProgression progression2) {
+                        PatchClassIntoFeatureOfReferenceClass(progression2, myClass, referenceClass, mylevel, loopPrevention);
+                    }
```
Comment (JohN100x1) [inline IsekaiMod/Utilities/PatchTools.cs:383]: @kjk001 Not sure if this is intended but `BlueprintProgression` is a subclass of `BlueprintFeature` so `PatchClassIntoFeatureOfReferenceClass` would be redunantly called twice if `fact` is a `BlueprintProgression`.

File: IsekaiMod/Utilities/PatchTools.cs [hunk 2]
```diff
@@ -0,0 +1,505 @@
...
+            }
+            // check if component is add facts because features could also be added as facts rather than on level...
+            if (component is AddFacts addFact) {
+                foreach (BlueprintUnitFact factRef in addFact.Facts) {
+                    if (factRef is BlueprintFeature feature2) {
+                        PatchClassIntoFeatureOfReferenceClass(feature2, myClass, referenceClass, mylevel, loopPrevention);
+                    }
+                    if (factRef is BlueprintProgression progression2) {
+                        PatchClassIntoFeatureOfReferenceClass(progression2, myClass, referenceClass, mylevel, loopPrevention);
+                    }
```
Comment (JohN100x1) [inline IsekaiMod/Utilities/PatchTools.cs:399]: Same issue here

File: IsekaiMod/Utilities/PatchTools.cs (hunk 1 above)
Comment (JohN100x1) [reply IsekaiMod/Utilities/PatchTools.cs:383]: Also `BlueprintFeature` is a subclass of `BlueprintUnitFact` so `HandleComponent` will be called for a `BlueprintFeature` and `BlueprintProgression`
